# NeuroSys Monitoring Agent Configuration Parameters

server.url=https://zestful-energy-production-5cb8.up.railway.app/api/v1
agent.lab.name=Lab-A
agent.collection.interval.seconds=5
agent.cache.dir=./cache
