version: '3.8'

services:
  neurosys-backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M

  neurosys-ai:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  neurosys-frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
