# NeuroSys Monitoring Agent Configuration Parameters

server.url=https://realtmesystemmonitoring-production.up.railway.app/api/v1
agent.lab.name=Lab-A
agent.collection.interval.seconds=1
agent.cache.dir=./cache
